src/main/java/domain/Post.java
package domain;

import javax.persistence.*;

import java.util.List;

/**
 * Post entity
 *
 * A post always gets posted by a user (see posterId)
 *
 * Note: using the named queries we won't be needing a @ManyToOne relation with the User entity :)
 */
@Entity
@Table(name = "Post")
@NamedQueries({
  @NamedQuery(
    name = "Post.findAllOrderedByDate",
    query = "SELECT p FROM Post p ORDER BY p.dateTime DESC"
  ),
  @NamedQuery(
    name = "Post.findAllFromUser",
    query = "SELECT p FROM Post p WHERE p.poster.id = :userId"
  ),
  @NamedQuery(
    name = "Post.findAllWhereContentLike",
    query = "SELECT p FROM Post p WHERE LOWER(p.content) LIKE LOWER(:content)"
  )
})
public class Post {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  private String content;

  private String dateTime;

  @ManyToOne    // ON DELETE CASCADE manually added in insert.sql script
  private User poster;

  @OneToMany(mappedBy = "ratedPost", cascade = { CascadeType.PERSIST })
  private List<Rating> ratings;

  public Post() {

  }

  public Post(Long id) {
    this.id = id;
  }

  public Post(String content, String dateTime) {
    this.content = content;
    this.dateTime = dateTime;
  }

  public Post(Long id, String content, String dateTime) {
    this.id = id;
    this.content = content;
    this.dateTime = dateTime;
  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public String getDateTime() {
    return dateTime;
  }

  public void setDateTime(String dateTime) {
    this.dateTime = dateTime;
  }

  public User getPoster() {
    return poster;
  }

  public void setPoster(User poster) {
    this.poster = poster;
  }

  public List<Rating> getRatings() {
    return ratings;
  }

  public void setRatings(List<Rating> ratings) {
    this.ratings = ratings;
  }

  public void addRating(Rating rating) {
    ratings.add(rating);
  }

  public void deleteRating(Long id) {
    this.ratings.removeIf(rating -> rating.getId().equals(id));
  }

  @Override
  public String toString() {
    return "id: " + id
      + " content: " + content
      + " dateTime: " + dateTime;
  }
}

src/main/java/domain/Rating.java
package domain;


import javax.persistence.*;

/**
 * Rating entity
 *
 * A post can have ratings, rated by a user.
 */
@Entity
@Table(name = "Rating")
public class Rating {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  @ManyToOne
  @JoinColumn(name = "USER_ID")
  private User rater;

  @ManyToOne    // ON DELETE CASCADE manually added in insert.sql script
  @JoinColumn(name = "POST_ID")
  private Post ratedPost;

  public Rating() {

  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public User getRater() {
    return rater;
  }

  public void setRater(User rater) {
    this.rater = rater;
  }

  public Post getRatedPost() {
    return ratedPost;
  }

  public void setRatedPost(Post ratedPost) {
    this.ratedPost = ratedPost;
  }

  @Override
  public String toString() {
    return "id: " + id
      + " post id: " + ratedPost.getId()
      + " user id: " + rater.getId();
  }
}

src/main/java/domain/User.java
package domain;

import javax.persistence.*;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * User entity
 *
 * Simple. Has some properties which needs to be saved.
 *
 * Checkout the auth named query, this one will be used to login a user.
 *
 * All relations are handled through Post and Follower entities.
 */
@Entity
@Table(name = "User")
@NamedQueries({
  @NamedQuery(name = "User.findAll", query = "SELECT u FROM User u"),
  @NamedQuery(name = "User.findByUsername", query = "SELECT u FROM User u WHERE u.username = :username"),
  @NamedQuery(
    name = "User.auth",
    query = "SELECT u FROM User u WHERE u.username = :username AND u.password = :password"
  ),
  @NamedQuery(
    name = "User.setIsConfirmed",
    query = "UPDATE User SET isConfirmed = 1 WHERE username = :username AND password = :password"
  )
})
public class User implements Serializable {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;

  @Column(unique = true, nullable = false)
  private String username;

  @Column(nullable = false)
  private String password;

  private String web;

  private String imageUrl;

  private String bio;

  @Column(name = "IS_CONFIRMED")
  private int isConfirmed;

  @ManyToMany(mappedBy = "follows", cascade = CascadeType.PERSIST)
  private List<User> followedBys = new ArrayList<>();

  @ManyToMany(cascade = CascadeType.PERSIST)
  private List<User> follows = new ArrayList<>();

  @OneToOne(mappedBy = "user", cascade = CascadeType.PERSIST)
  private UserRole role;

  @PrePersist
  public void prePersist() {
    if (this.role == null) {
      this.role = new UserRole("user", this);
    }

    isConfirmed = 0;
  }

  public User() {

  }

  public User(Long id) {
    this.id = id;
  }


  public User(String username, String password) {
    this.username = username;
    this.password = password;
  }

  public User(Long id, String username, String password) {
    this.id = id;
    this.username = username;
    this.password = password;
  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public String getWeb() {
    return web;
  }

  public void setWeb(String web) {
    this.web = web;
  }

  public String getImageUrl() {
    return imageUrl;
  }

  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  public String getBio() {
    return bio;
  }

  public void setBio(String bio) {
    this.bio = bio;
  }

  public List<User> getFollowedBys() {
    return followedBys;
  }

  public void setFollowedBys(List<User> followedBys) {
    this.followedBys = followedBys;
  }

  public void addFollowedBy(User followedBy) {
    followedBys.add(followedBy);
  }

  public void removeFollowedBy(User followedBy) {
    followedBys.remove(followedBy);
  }

  public List<User> getFollows() {
    return follows;
  }

  public void setFollows(List<User> follows) {
    this.follows = follows;
  }

  public void addFollow(User follow) {
    follows.add(follow);
  }

  public void removeFollow(User follow) {
    follows.remove(follow);
  }

  public UserRole getRole() {
    return role;
  }

  public void setRole(UserRole role) {
    this.role = role;
  }

  public int getIsConfirmed() {
    return isConfirmed;
  }

  public void setIsConfirmed(int isConfirmed) {
    this.isConfirmed = isConfirmed;
  }

  public void follow(User follow) {
    if (!follows.contains(follow)) {
      follows.add(follow);
      follow.addFollowedBy(this);
    }
  }

  public void unFollow(User follow) {
    if (follows.contains(follow)) {
      follows.remove(follow);
      follow.removeFollow(this);
    }
  }

  @Override
  public String toString() {
    return "id: " + id
      + " username: " + username
      + " password: " + password
      + " web: " + web
      + " bio: " + bio
      + " imageUrl: " + imageUrl;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (!(o instanceof User)) return false;
    return id != null && id.equals(((User) o).id);
  }

  @Override
  public int hashCode() {
    return 31;
  }
}

src/main/java/domain/UserRole.java
package domain;

import javax.persistence.*;

import java.io.Serializable;
import java.util.List;

@Entity
@Table(name = "User_Role")
public class UserRole implements Serializable {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private long id;

  private String role;

  public User getUser() {
    return user;
  }

  public void setUser(User user) {
    this.user = user;
  }

  @OneToOne
  @JoinColumn(name = "USERNAME", referencedColumnName = "USERNAME")
  private User user;  // ON DELETE CASCADE manually added in insert.sql script

  public UserRole() {

  }

  public UserRole(String role, User user) {
    this.role = role;
    this.user = user;
  }

  public long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }
}

src/main/java/dto/FollowerDto.java
package dto;

import domain.User;

public class FollowerDto {
  private Long id;
  private String username;
  private String imageUrl;

  public FollowerDto(Long id, String username, String imageUrl) {
    this.id = id;
    this.username = username;
    this.imageUrl = imageUrl;
  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getImageUrl() {
    return imageUrl;
  }

  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }

  public static FollowerDto fromUser(User follower) {
    return new FollowerDto(
      follower.getId(),
      follower.getUsername(),
      follower.getImageUrl()
    );
  }
}

src/main/java/dto/PostDto.java
package dto;

import domain.Post;
import utils.Constants;

import java.util.List;
import java.util.stream.Collectors;

public class PostDto {
  private static final String API_POSTS_URL = Constants.BASE_API_URL + "posts/";
  private static final String API_RATINGS_URL = API_POSTS_URL + "ratings/";

  private Long id;
  private String content;
  private String dateTime;
  private UserDto poster;
  private List<RatingDto> ratings;

  private String updateLink;
  private String deleteLink;
  private String postRatingLink;

  public PostDto(Long id, String content, String dateTime, UserDto poster, List<RatingDto> ratings) {
    this.id = id;
    this.content = content;
    this.dateTime = dateTime;
    this.poster = poster;
    this.ratings = ratings;

    this.constructLinks();
  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getContent() {
    return content;
  }

  public void setContent(String content) {
    this.content = content;
  }

  public String getDateTime() {
    return dateTime;
  }

  public void setDateTime(String dateTime) {
    this.dateTime = dateTime;
  }

  public UserDto getPoster() {
    return poster;
  }

  public void setPoster(UserDto poster) {
    this.poster = poster;
  }

  public List<RatingDto> getRatings() {
    return ratings;
  }

  public void setRatings(List<RatingDto> ratings) {
    this.ratings = ratings;
  }

  public String getUpdateLink() {
    return updateLink;
  }

  public String getDeleteLink() {
    return deleteLink;
  }

  public String getPostRatingLink() {
    return postRatingLink;
  }

  private void constructLinks() {
    updateLink = API_POSTS_URL;
    deleteLink = API_POSTS_URL + String.valueOf(id);
    postRatingLink = API_RATINGS_URL + String.valueOf(id);
  }

  public static PostDto fromPost(Post post) {
    return new PostDto(
      post.getId(),
      post.getContent(),
      post.getDateTime(),
      UserDto.fromUserWithoutFollowers(post.getPoster()),
      post.getRatings().stream().map(RatingDto::fromRating).collect(Collectors.toList())
    );
  }
}

src/main/java/dto/RatingDto.java
package dto;

import domain.Rating;
import utils.Constants;

public class RatingDto {
  private static final String API_RATINGS_URL = Constants.BASE_API_URL + "posts/ratings/";

  private Long id;
  private Long postId;
  private Long userId;

  private String deleteLink;

  public RatingDto() {
    this.constructLinks();
  }

  public RatingDto(Long postId, Long userId) {
    this.id = id;
    this.postId = postId;
    this.userId = userId;

    this.constructLinks();
  }

  public RatingDto(Long id, Long postId, Long userId) {
    this.id = id;
    this.postId = postId;
    this.userId = userId;

    this.constructLinks();
  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public Long getPostId() {
    return postId;
  }

  public void setPostId(Long postId) {
    this.postId = postId;
  }

  public Long getUserId() {
    return userId;
  }

  public void setUserId(Long userId) {
    this.userId = userId;
  }

  public String getDeleteLink() {
    return deleteLink;
  }

  private void constructLinks() {
    this.deleteLink = API_RATINGS_URL + String.valueOf(postId) + "/" + String.valueOf(id);
  }

  public static RatingDto fromRating(Rating rating) {
    return new RatingDto(
      rating.getId(),
      rating.getRatedPost().getId(),
      rating.getRater().getId()
    );
  }
}

src/main/java/dto/UserRoleDto.java
package dto;

import domain.UserRole;

public class UserRoleDto {
  private Long id;
  private String role;

  public UserRoleDto(Long id, String role) {
    this.id = id;
    this.role = role;
  }

  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public static UserRoleDto fromUserRole(UserRole role) {
    return new UserRoleDto(
      role.getId(),
      role.getRole()
    );
  }
}

src/main/java/controller/AdminController.java
package controller;

import dto.PostDto;
import dto.UserDto;
import service.PostService;
import service.UserService;

import javax.enterprise.context.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import java.util.List;
import java.util.stream.Collectors;

@Named
@RequestScoped
public class AdminController {
  @Inject
  private UserService userService;

  @Inject
  private PostService postService;

  public AdminController() {

  }

  /**
   * Will logout a user by removing it from the session and redirect back to login
   *
   * @return    string to the page we want to redirect to (login)
   */
  public String logout() {
    FacesContext context = FacesContext.getCurrentInstance();
    HttpServletRequest request = (HttpServletRequest) context.getExternalContext().getRequest();
    HttpSession session = (HttpSession) context.getExternalContext().getSession(false);

    try {
      request.logout();
      session.invalidate();
    } catch (ServletException e) {
      e.printStackTrace();
    }

    return "login?faces-redirect=true";
  }

  /**
   * Will get all posts (ordered by date DESC)
   *
   * @see PostService#findAllPostsOrderedByDate()
   */
  public List<PostDto> getAllPosts() {
    return postService.findAllPostsOrderedByDate().stream().map(PostDto::fromPost).collect(Collectors.toList());
  }

  /**
   * @see PostService#delete(Long)
   */
  public void deletePost(Long id) {
    postService.delete(id);
  }

  /**
   * @see UserService#getUsers()
   */
  public List<UserDto> getUsers() {
    return userService.getUsers().stream().map(UserDto::fromUser).collect(Collectors.toList());
  }

  /**
   * @see UserService#delete(Long)
   */
  public void deleteUser(Long id) {
    userService.delete(id);
  }

  /**
   * @see UserService#switchUserRole(Long)
   */
  public void switchUserRole(Long id) {
    userService.switchUserRole(id);
  }
}

src/main/java/controller/LoginController.java
package controller;

import domain.User;
import service.UserService;

import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
import java.io.Serializable;
import java.security.Principal;
import java.util.Map;

@Named
@SessionScoped
public class LoginController implements Serializable {
  private String username;
  private String password;

  @Inject
  private UserService userService;

  public LoginController() {

  }

  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getPassword() {
    return password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public String submitLogin() {
    FacesContext context = FacesContext.getCurrentInstance();
    ExternalContext externalContext = context.getExternalContext();
    HttpServletRequest request = (HttpServletRequest) externalContext.getRequest();

    try {
      request.login(username, password);
    } catch (ServletException e) {
      context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "Login failed!", null));

      return "login";
    }

    Principal principal = request.getUserPrincipal();
    User auth = userService.getUserByUsername(principal.getName());

    if (auth.getRole().getRole().equals("admin")) {
      externalContext.getSessionMap().put("user", auth);                    // <-- set auth in session
      return "admin?faces-redirect=true";                                   // <-- redirect admin
    } else {
      context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, "You\'ve no permissions!", null));

      return "login";
    }
  }
}

src/main/webapp/admin.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:c="http://java.sun.com/jsp/jstl/core"
      xmlns:h="http://java.sun.com/jsf/html">
  <h:head>
    <title>Kwetter admin</title>
    <h:outputStylesheet name="style.css" />
  </h:head>
  <h:body>
    <b:navBar fluid="true" styleClass="header-nav">
      <b:navbarLinks pull="right" styleClass="hidden-xs">
        <b:form class="navbar-form navbar-left hidden-md hidden-sm hidden-xs">
          <b:commandButton
            look="primary btn-block"
            value="logout"
            icon="log-out"
            size="s"
            action="#{adminController.logout}" />
        </b:form>
      </b:navbarLinks>
    </b:navBar>

    <b:container fluid="true" styleClass="jumbotron-wrapper">
      <b:jumbotron>
        <h1>Admin control</h1>
      </b:jumbotron>
    </b:container>
    <b:container>
      <b:panelGrid colSpans="8,4" size="sm">
        <b:panel title="Kwetters" showCollapseLink="true" look="default">
          <c:forEach var="post" items="#{adminController.allPosts}">
            <b:panel>
              <div class="post-panel-body">
                <h5>#{post.poster.username}</h5>
                <p>#{post.content}</p>
                <h:outputText value="#{post.dateTime}" >
                  <f:convertDateTime pattern="dd.MM.yyyy HH:mm" />
                </h:outputText>
                <f:facet name="footer">
                  <h:form>
                    <div class="panel-footer-button-toolbar">
                      <b:commandButton
                        look="danger"
                        icon="trash"
                        value=""
                        action="#{adminController.deletePost(post.id)}" />
                    </div>
                  </h:form>
                </f:facet>
              </div>
            </b:panel>
          </c:forEach>
        </b:panel>
        <b:panel title="Users" showCollapseLink="true" look="default">
          <c:forEach var="user" items="#{adminController.users}">
            <b:panel>
              <div class="user-panel-body">
                <b:image name="test" value="#{user.imageUrl}" />
                <div class="user-info-wrapper">
                  <div class="user-info-row">
                    <span>Username: </span>
                    <span>#{user.username}</span>
                  </div>
                  <div class="user-info-row">
                    <span>Role: </span>
                    <span>#{user.role.role}</span>
                  </div>
                </div>
                <div class="user-info-row">
                  <span>Web: </span>
                  <span>#{user.web}</span>
                </div>
                <div class="user-info-row">
                  <span>Bio: </span>
                  <span style="width: 100%">#{user.bio}</span>
                </div>
              </div>
              <f:facet name="footer">
                <h:form>
                  <div class="panel-footer-button-toolbar">
                    <b:commandButton
                      look="danger"
                      icon="trash"
                      value=""
                      style="margin-right: 10px"
                      action="#{adminController.deleteUser(user.id)}" />
                    <b:commandButton
                      look="warning"
                      icon="pencil"
                      value="switch role"
                      action="#{adminController.switchUserRole(user.id)}" />
                  </div>
                </h:form>
              </f:facet>
            </b:panel>
          </c:forEach>
        </b:panel>
      </b:panelGrid>
    </b:container>
  </h:body>
</html>

src/main/webapp/index.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
  PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">

<h:head>
  <title>Admin</title>
</h:head>

<h:body>
  Secured part of the page
</h:body>
</html>

src/main/webapp/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
  <h:head>
    <title>Kwetter admin login</title>
    <h:outputStylesheet name="style.css" />
  </h:head>
  <h:body>
    <b:container>
      <h:form id="login-form" styleClass="form-login" prependId="false">
        <h2 class="form-signin-heading">Admin login</h2>
        <b:inputText
          id="username"
          placeholder="Username"
          name="username"
          autocomplete="off"
          value="#{loginController.username}">
          <f:facet name="prepend">
            <b:icon name="user" />
          </f:facet>
        </b:inputText>
        <b:inputText
          id="password"
          placeholder="Password"
          name="password"
          type="password"
          autocomplete="off"
          value="#{loginController.password}">
          <f:facet name="prepend">
            <b:iconAwesome name="key" />
          </f:facet>
        </b:inputText>
        <b:commandButton
          look="primary btn-block"
          value="login"
          icon="log-in"
          size="s"
          action="#{loginController.submitLogin}" />
          <b:messages />
      </h:form>
    </b:container>
  </h:body>
</html>